document.writeln("<div class=\'bottom-publicBox\'>");
document.writeln("    <div class=\'bottom-publicBar\'>");
document.writeln("        <div class=\'bottom-public\'>");
document.writeln("            <h1>Global One-stop Service Platform For Pan-Internet Application</h1>");
document.writeln("            <p>");
document.writeln("                MIRACLE GAMES platform is a service platform that focuses on Windows 10 terminal applications and games promotion. Our goal is to help developers quickly acquire users and realize their presence in Windows 10 market.");
document.writeln("            </p>");
document.writeln("        </div>");
document.writeln("    </div>");
document.writeln("</div>");
document.writeln("<div class=\'bottomIn-bar\'>");
document.writeln("    <div class=\'bottomIn\'>");
document.writeln("        <div class=\'bottomIn-itemBar\'>");
document.writeln("");
document.writeln("            <div class=\'bottomIn-item\'>");
document.writeln("                <h2>About Us</h2>");
document.writeln("                <ul class=\'bottomIn-Con\'>");
document.writeln("                    <li>");
document.writeln("                        <a href=\'javascript:void(0)\'>Press Site</a>");
document.writeln("                    </li>");
document.writeln("                    <li>");
document.writeln("                        <a href=\'join.html\' target=\'_blank\'>Join Us</a>");
document.writeln("                    </li>");
document.writeln("                    <li>");
document.writeln("                        <a href=\'javascript:void(0)\'>Friend Links</a>");
document.writeln("                    </li>");
document.writeln("                </ul>");
document.writeln("            </div>");
document.writeln("");
document.writeln("");
document.writeln("            <div class=\'bottomIn-item\'>");
document.writeln("                <h2>Developer Service</h2>");
document.writeln("                <ul class=\'bottomIn-Con\'>");
document.writeln("                    <li>");
document.writeln("                        <a href=\'https://dev.mguwp.net/main/index\' target=\'_blank\'>Registration</a>");
document.writeln("                    </li>");
document.writeln("                    <li>");
document.writeln("                        <a href=\'http://doc.mguwp.net/en/\' target=\'_blank\'>Documents</a>");
document.writeln("                    </li>");
document.writeln("                    <li>");
document.writeln("                        <a href=\'javascript:void(0)\'>Tech Forum</a>");
document.writeln("                    </li>");
document.writeln("                </ul>");
document.writeln("            </div>");
document.writeln("");
document.writeln("");
document.writeln("            <div class=\'bottomIn-item bottomIn-item-right\'>");
document.writeln("                <h2>Social Networking</h2>");
document.writeln("                <ul class=\'bottomIn-abroad\'>");
document.writeln("                    <li>");
document.writeln("                        <a href=\'https://www.facebook.com/MiracleGamesINC/\' target=\'_blank\'>");
document.writeln("                            <img src=\'images/facebook.png\'>");
document.writeln("                            <span>Facebook</span>");
document.writeln("                        </a>");
document.writeln("                    </li>");
document.writeln("                    <li>");
document.writeln("                        <a href=\'javascript:void(0)\'>");
document.writeln("                            <img src=\'images/youtube.png\'>");
document.writeln("                            <span>YouTube</span>");
document.writeln("                        </a>");
document.writeln("                    </li>");
document.writeln("                    <li>");
document.writeln("                        <a href=\'javascript:void(0)\'>");
document.writeln("                            <img src=\'images/twitter.png\'>");
document.writeln("                            <span>Twitter</span>");
document.writeln("                        </a>");
document.writeln("                    </li>");
document.writeln("                    <li>");
document.writeln("                        <a href=\'javascript:void(0)\'>");
document.writeln("                            <img src=\'images/instagram.png\'>");
document.writeln("                            <span>Instagram</span>");
document.writeln("                        </a>");
document.writeln("                    </li>");
document.writeln("                </ul>");
document.writeln("            </div>");
document.writeln("");
document.writeln("        </div>");
document.writeln("        <div class=\'bottomIn-mid\'>");
document.writeln("            <div class=\'bottomIn-mid1\'></div>");
document.writeln("            <div class=\'bottomIn-mid2\'></div>");
document.writeln("        </div>");
document.writeln("        <div class=\'bottomIn-copy\'>");
document.writeln("            <p>COPYRIGHT© 2016 MIRACLE GAMES INC ALL RIGHTS RESERVED. </p>");
document.writeln("        </div>");
document.writeln("    </div>");
document.writeln("</div>");