document.writeln("<div class=\'bottomIn-bar\'>");
document.writeln("    <div class=\'bottomIn\'>");
document.writeln("        <div class=\'bottomIn-itemBar\'>");
document.writeln("            <div class=\'bottomIn-item\'>");
document.writeln("                <h2>关于我们</h2>");
document.writeln("                <ul class=\'bottomIn-Con\'>");
document.writeln("                    <li>");
document.writeln("                        <a href=\'javascript:void(0)\'>公司动态</a>");
document.writeln("                    </li>");
document.writeln("                    <li>");
document.writeln("                        <a href=\'http://www.mguwp.net/join.html\' target=\'_blank\'>加入我们</a>");
document.writeln("                    </li>");
document.writeln("                    <li>");
document.writeln("                        <a href=\'javascript:void(0)\'>友情链接</a>");
document.writeln("                    </li>");
document.writeln("                </ul>");
document.writeln("            </div>");
document.writeln("            <div class=\'bottomIn-item\'>");
document.writeln("                <h2>开发者服务</h2>");
document.writeln("                <ul class=\'bottomIn-Con\'>");
document.writeln("                    <li>");
document.writeln("                        <a href=\'http://dev.mguwp.net/main/index\' target=\'_blank\'>注册登录</a>");
document.writeln("                    </li>");
document.writeln("                    <li>");
document.writeln("                        <a href=\'http://doc.mguwp.net/\' target=\'_blank\'>文档中心</a>");
document.writeln("                    </li>");
document.writeln("                    <li>");
document.writeln("                        <a href=\'javascript:void(0)\'>技术论坛</a>");
document.writeln("                    </li>");
document.writeln("                </ul>");
document.writeln("            </div>");
document.writeln("            <div class=\'bottomIn-weChat\'>");
document.writeln("                <img src=\'images/weChat.jpg\'>");
document.writeln("                <p>MIRACLE GAMES</p>");
document.writeln("                <P>微信公众号</P>");
document.writeln("            </div>");
document.writeln("        </div>");
document.writeln("        <div class=\'bottomIn-mid\'>");
document.writeln("            <div class=\'bottomIn-mid1\'></div>");
document.writeln("            <div class=\'bottomIn-mid2\'></div>");
document.writeln("        </div>");
document.writeln("        <div class=\'bottomIn-copy\'>");
document.writeln("            <p>北京奇游灵动科技有限公司版权所有 COPYRIGHT© 2016 MIRACLE GAMES LIMITED. ALL RIGHTS RESERVED.</p>");
document.writeln("            <p>京ICP备16022485号-2 | 京网文[2017]1979-172号</p>");
document.writeln("        </div>");
document.writeln("    </div>");
document.writeln("</div>");