document.writeln("<div id=\'roof\' class=\'roof\'>");
document.writeln("    <div class=\'roof-box\'>");
document.writeln("        <div class=\'roof-bar\'>");
document.writeln("            <div class=\'roof-logo\'>");
document.writeln("                <a href=\'principal.html\' class=\'roof-logo-link\'>");
document.writeln("                    <img src=\'images/roof-logo.png\'>");
document.writeln("                </a>");
document.writeln("            </div>");
document.writeln("            <div class=\'roof-sign\'>");
document.writeln("                <div class=\'roof-sign-bar\'>");
document.writeln("                    <a class=\'roof-register\' href=\'http://dev.mguwp.net/main/registerIndex\' target=\'_blank\'>注册</a>");
document.writeln("                    <a class=\'roof-login\' href=\'http://dev.mguwp.net\' target=\'_blank\'>登录</a>");
document.writeln("                </div>");
document.writeln("            </div>");
document.writeln("            <div class=\'roof-nav\'>");
document.writeln("                <ul class=\'roof-nav-bar\' id=\'roof-nav-bar\'>");
document.writeln("                    <li class=\'roof-nav-sort\'>");
document.writeln("                        <a href=\'principal.html\' class=\'roof-nav-content\'>");
document.writeln("                            首页");
document.writeln("                            <span>&nbsp;</span>");
document.writeln("                        </a>");
document.writeln("                    </li>");
document.writeln("                    <li class=\'roof-nav-sort\'>");
document.writeln("                        <a href=\'advertisers.html\' class=\'roof-nav-content\'>");
document.writeln("                            广告主");
document.writeln("                            <span>&nbsp;</span>");
document.writeln("                        </a>");
document.writeln("                    </li>");
document.writeln("                    <li class=\'roof-nav-sort\'>");
document.writeln("                        <a href=\'developers.html\' class=\'roof-nav-content\'>");
document.writeln("                            开发者");
document.writeln("                            <span>&nbsp;</span>");
document.writeln("                        </a>");
document.writeln("                    </li>");
document.writeln("                    <li class=\'roof-nav-sort\'>");
document.writeln("                        <a href=\'receive.html\' class=\'roof-nav-content\'>");
document.writeln("                            广告SDK");
document.writeln("                            <span>&nbsp;</span>");
document.writeln("                        </a>");
document.writeln("                    </li>");
document.writeln("                    <li class=\'roof-nav-sort\'>");
document.writeln("                        <a href=\'platform.html\' class=\'roof-nav-content\'>");
document.writeln("                            数据管理");
document.writeln("                            <span>&nbsp;</span>");
document.writeln("                        </a>");
document.writeln("                    </li>");
document.writeln("                    <li class=\'roof-nav-sort\'>");
document.writeln("                        <a href=\'javascript:void(0)\' class=\'roof-nav-content\' id=\'roof-nav-cursor\'>");
document.writeln("                            关于我们");
document.writeln("                            <span>&nbsp;</span>");
document.writeln("                        </a>");
document.writeln("                        <ul class=\'roof-nav-sub-item\'>");
document.writeln("                            <li>");
document.writeln("                                <a href=\'http://www.mguwp.net/introduce.html\' target=\'_blank\'>关于MG</a>");
document.writeln("                            </li>");
document.writeln("                            <li>");
document.writeln("                                <a href=\'http://www.mguwp.net/join.html\' target=\'_blank\'>招贤纳士</a>");
document.writeln("                            </li>");
document.writeln("                            <li>");
document.writeln("                                <a href=\'http://www.mguwp.net/contact.html\' target=\'_blank\'>联系我们</a>");
document.writeln("                            </li>");
document.writeln("                        </ul>");
document.writeln("                    </li>");
document.writeln("                </ul>");
document.writeln("            </div>");
document.writeln("        </div>");
document.writeln("    </div>");
document.writeln("</div>");