document.writeln("<div class=\'bottomIn-bar\'>");
document.writeln("    <div class=\'bottomIn\'>");
document.writeln("        <div class=\'bottomIn-itemBar\'>");
document.writeln("");
document.writeln("            <div class=\'bottomIn-item\'>");
document.writeln("                <h2>About Us</h2>");
document.writeln("                <ul class=\'bottomIn-Con\'>");
document.writeln("                    <li>");
document.writeln("                        <a href=\'javascript:void(0)\'>Press Site</a>");
document.writeln("                    </li>");
document.writeln("                    <li>");
document.writeln("                        <a href=\'https://www.mguwp.net/en/join.html\' target=\'_blank\'>Join Us</a>");
document.writeln("                    </li>");
document.writeln("                    <li>");
document.writeln("                        <a href=\'javascript:void(0)\'>Friend Links</a>");
document.writeln("                    </li>");
document.writeln("                </ul>");
document.writeln("            </div>");
document.writeln("");
document.writeln("");
document.writeln("            <div class=\'bottomIn-item\'>");
document.writeln("                <h2>Developer Service</h2>");
document.writeln("                <ul class=\'bottomIn-Con\'>");
document.writeln("                    <li>");
document.writeln("                        <a href=\'https://dev.mguwp.net/main/index\' target=\'_blank\'>Registration</a>");
document.writeln("                    </li>");
document.writeln("                    <li>");
document.writeln("                        <a href=\'http://doc.mguwp.net/en/\' target=\'_blank\'>Documents</a>");
document.writeln("                    </li>");
document.writeln("                    <li>");
document.writeln("                        <a href=\'javascript:void(0)\'>Tech Forum</a>");
document.writeln("                    </li>");
document.writeln("                </ul>");
document.writeln("            </div>");
document.writeln("");
document.writeln("");
document.writeln("            <div class=\'bottomIn-item bottomIn-item-right\'>");
document.writeln("                <h2>Social Networking</h2>");
document.writeln("                <ul class=\'bottomIn-abroad\'>");
document.writeln("                    <li>");
document.writeln("                        <a href=\'https://www.facebook.com/MiracleGamesINC/\' target=\'_blank\'>");
document.writeln("                            <img src=\'images/facebook.png\'>");
document.writeln("                            <span>Facebook</span>");
document.writeln("                        </a>");
document.writeln("                    </li>");
document.writeln("                </ul>");
document.writeln("            </div>");
document.writeln("");
document.writeln("        </div>");
document.writeln("        <div class=\'bottomIn-mid\'>");
document.writeln("            <div class=\'bottomIn-mid1\'></div>");
document.writeln("            <div class=\'bottomIn-mid2\'></div>");
document.writeln("        </div>");
document.writeln("        <div class=\'bottomIn-copy\'>");
document.writeln("            <p>COPYRIGHT© 2016 MIRACLE GAMES INC ALL RIGHTS RESERVED. </p>");
document.writeln("            <p>Beijing ICP 16022485-2 | Article [2017]1979-172</p>");
document.writeln("        </div>");
document.writeln("    </div>");
document.writeln("</div>");