document.writeln("<div class=\'footer-dec\'>");
document.writeln("</div>");
document.writeln("<footer class=\'footer\'>");
document.writeln("    <div class=\'f_box\'>");
document.writeln("");
document.writeln("        <div class=\'f_chain\'>");
document.writeln("            <div class=\'f_item f_item_less\'>");
document.writeln("                <h3 class=\'f_item_title\'>MIRACLE GAMES</h3>");
document.writeln("                <ul class=\'f_item_list\'>");
document.writeln("                    <li>");
document.writeln("                        <a href=\'privacyAgreement\' target=\'_blank\'>Privacy Policy</a>");
document.writeln("                    </li>");
document.writeln("                    <li>");
document.writeln("                        <a href=\'subscriberAgreement\' target=\'_blank\'>Terms of Service</a>");
document.writeln("                    </li>");
document.writeln("                    <li>");
document.writeln("                        <a href=\'http://mguwp.net/en/join.html\' target=\'_blank\'>Join Us</a>");
document.writeln("                    </li>");
document.writeln("                </ul>");
document.writeln("            </div>");
document.writeln("            <div class=\'f_item\'>");
document.writeln("                <h3 class=\'f_item_title\'>Social Networking</h3>");
document.writeln("                <ul class=\'f_item_social\'>");
document.writeln("                    <li>");
document.writeln("                        <a href=\'https://www.facebook.com/MiracleGamesStore\' target=\'_blank\'>");
document.writeln("                            <i></i>");
document.writeln("                            <span>Facebook</span>");
document.writeln("                        </a>");
document.writeln("                    </li>");
document.writeln("                    <li>");
document.writeln("                        <a href=\'https://www.youtube.com/channel/UCnD8zYpFgOr0hCLHfdxufSQ/\' target=\'_blank\'>");
document.writeln("                            <i class=\'f_item_youtube\'></i>");
document.writeln("                            <span>YouTube</span>");
document.writeln("                        </a>");
document.writeln("                    </li>");
document.writeln("                    <li>");
document.writeln("                        <a href=\'https://twitter.com/SMiraclegames\' target=\'_blank\'>");
document.writeln("                            <i class=\'f_item_twitter\'></i>");
document.writeln("                            <span>Twitter</span>");
document.writeln("                        </a>");
document.writeln("                    </li>");
document.writeln("                    <li>");
document.writeln("                        <a href=\'https://www.instagram.com/store.miraclegames/\' target=\'_blank\'>");
document.writeln("                            <i class=\'f_item_ins\'></i>");
document.writeln("                            <span>Instagram</span>");
document.writeln("                        </a>");
document.writeln("                    </li>");
document.writeln("                </ul>");
document.writeln("            </div>");
document.writeln("            <div class=\'f_item\'>");
document.writeln("                <h3 class=\'f_item_title\'>Customer Service </h3>");
document.writeln("                <ul class=\'f_item_contact\'>");
document.writeln("                    <li>");
document.writeln("                        <a href=\'mailto:Support@mguwp.com\'>");
document.writeln("                            <i></i>");
document.writeln("                            <span>Mail: Support@mguwp.com</span>");
document.writeln("                        </a>");
document.writeln("                    </li>");
document.writeln("                    <li>");
document.writeln("                        <a href=\'skype:live:mg20151203?chat\'>");
document.writeln("                            <i class=\'f_item_contact_sky\'></i>");
document.writeln("                            <span>Skype: MG20151203@outlook.com</span>");
document.writeln("                        </a>");
document.writeln("                    </li>");
document.writeln("                </ul>");
document.writeln("            </div>");
document.writeln("");
document.writeln("            <div class=\'h_lang\'>");
document.writeln("                <div class=\'h_lang_con\'>");
document.writeln("                    <div class=\'h_lang_txt h_lang_txt_reversed\'>EN</div>");
document.writeln("                    <div class=\'h_lang_icon h_lang_icon_reversed\'></div>");
document.writeln("                </div>");
document.writeln("                <div class=\'h_lang_down h_lang_down_reversed\'></div>");
document.writeln("            </div>");
document.writeln("        </div>");
document.writeln("");
document.writeln("        <div class=\'f_dec\'></div>");
document.writeln("");
document.writeln("        <p class=\'f_copyright\'>");
document.writeln("            COPYRIGHT© 2016 MIRACLE GAMES INC ALL RIGHTS RESERVED.");
document.writeln("        </p>");
document.writeln("    </div>");
document.writeln("</footer>");