document.writeln("<header class=\'header\'>");
document.writeln("    <div class=\'h_box\'>");
document.writeln("        <!--头部左边-->");
document.writeln("        <a href=\'index.html\' class=\'h_logo\'>");
document.writeln("            <img src=\'images/logo.png\'>");
document.writeln("        </a>");
document.writeln("        <div class=\'h_dec h_dec_l\'></div>");
document.writeln("        <div class=\'h_mail\'>");
document.writeln("            <span class=\'h_mail_icon\'>&nbsp;</span>");
document.writeln("            <span class=\'h_mail_title\'>Mail:</span>");
document.writeln("            <span>Support@mguwp.com</span>");
document.writeln("        </div>");
document.writeln("        <!--头部右边-->");
document.writeln("        <div class=\'h_lang\'>");
document.writeln("            <div class=\'h_lang_con\'>");
document.writeln("                <div class=\'h_lang_txt\'>EN</div>");
document.writeln("                <div class=\'h_lang_icon\'></div>");
document.writeln("            </div>");
document.writeln("            <div class=\'h_lang_down\'></div>");
document.writeln("        </div>");
document.writeln("        <div class=\'h_dec\'></div>");
document.writeln("        <div class=\'h_plat\'>");
document.writeln("            <span class=\'h_plat_icon\'>&nbsp;</span>");
document.writeln("            <span class=\'h_plat_txt\'>MG Open Platform</span>");
document.writeln("        </div>");
document.writeln("        <div class=\'h_client\'>");
document.writeln("            <span class=\'h_client_icon\'>&nbsp;</span>");
document.writeln("            <span class=\'h_client_txt\'>Install Client</span>");
document.writeln("        </div>");
document.writeln("        <div class=\'h_enter\'>");
document.writeln("            <a class=\'h_login\'>Login</a>");
document.writeln("            <span class=\'h_enter_dec\'>|</span>");
document.writeln("            <a class=\'h_login\'>Sign up</a>");
document.writeln("        </div>");
document.writeln("        <div class=\'h_social\'>");
document.writeln("            <span>Share:</span>");
document.writeln("            <a>&nbsp;</a>");
document.writeln("            <a class=\'h_twi\'>&nbsp;</a>");
document.writeln("            <a class=\'h_ins\'>&nbsp;</a>");
document.writeln("        </div>");
document.writeln("    </div>");
document.writeln("</header>");