document.writeln("<header class=\'header\'>");
document.writeln("    <div class=\'h_box\'>");
document.writeln("        <!--头部左边-->");
document.writeln("        <a href=\'index.html\' class=\'h_logo\'>");
document.writeln("            <img src=\'images/logo.png\'>");
document.writeln("        </a>");
document.writeln("        <div class=\'h_dec h_dec_l\'></div>");
document.writeln("        <a class=\'h_mail\' href=\'mailto:Support@mguwp.com\'>");
document.writeln("            <span class=\'h_mail_icon\'>&nbsp;</span>");
document.writeln("            <span class=\'h_mail_title\'>Mail:</span>");
document.writeln("            <span>Support@mguwp.com</span>");
document.writeln("        </a>");
document.writeln("        <!--头部右边-->");
document.writeln("        <div class=\'h_lang\' title=\'Coming soon...\'>");
document.writeln("            <div class=\'h_lang_con\'>");
document.writeln("                <div class=\'h_lang_txt\'>EN</div>");
document.writeln("                <div class=\'h_lang_icon\'></div>");
document.writeln("            </div>");
document.writeln("            <a href=\'javascript:void(0)\' class=\'h_lang_down\'></a>");
document.writeln("        </div>");
document.writeln("        <div class=\'h_dec\'></div>");
document.writeln("        <a href=\'http://www.mguwp.com/en/index.html\' target=\'_blank\' class=\'h_plat\'>");
document.writeln("            <span class=\'h_plat_icon\'>&nbsp;</span>");
document.writeln("            <span class=\'h_plat_txt\'>MG Open Platform</span>");
document.writeln("        </a>");
document.writeln("        <a href=\'javascript:void(0)\' title=\'Coming soon...\' class=\'h_client\'>");
document.writeln("            <span class=\'h_client_icon\'>&nbsp;</span>");
document.writeln("            <span class=\'h_client_txt\'>Install Client</span>");
document.writeln("        </a>");
document.writeln("        <div class=\'h_enter\'>");
document.writeln("            <a href=\'javascript:void(0)\' title=\'Coming soon...\' class=\'h_login\'>Login</a>");
document.writeln("            <span class=\'h_enter_dec\'>|</span>");
document.writeln("            <a href=\'javascript:void(0)\' title=\'Coming soon...\'  class=\'h_login\'>Sign up</a>");
document.writeln("        </div>");
document.writeln("        <div class=\'h_social\'>");
document.writeln("            <span>Share:</span>");
document.writeln("            <a href=\'http://www.facebook.com/sharer/sharer.php?u=https://store.mguwp.com/\' target=\'_blank\' title=\'facebook\'>&nbsp;</a>");
document.writeln("            <a href=\'http://twitter.com/home?status=https://store.mguwp.com/\' target=\'_blank\' title=\'twitter\' class=\'h_twi\'>&nbsp;</a>");
document.writeln("            <!--");
document.writeln("            这个twitter只分享网址");
document.writeln("            <a href=\'http://twitter.com/share?url=https://store.mguwp.com/\' target=\'_blank\' title=\'twitter\' class=\'h_twi\'>&nbsp;</a>-->");
document.writeln("            <!--<a href=\'javascript:void(0)\' title=\'YouTube\' class=\'h_youtube\'>&nbsp;</a>-->");
document.writeln("        </div>");
document.writeln("    </div>");
document.writeln("</header>");