document.writeln("<div class=\'bottom-publicBox\'>");
document.writeln("    <div class=\'bottom-publicBar\'>");
document.writeln("        <div class=\'bottom-public\'>");
document.writeln("            <h1>Digitalization helps Chinese pan-net developers to dive deeply into global market. </h1>");
document.writeln("            <p>");
document.writeln("                MIRACLE GAMES platform is a service platform that focuses on Windows 10 terminal applications and games promotion. Our goal is to help developers quickly acquire users and realize their presence in Windows 10 market. ");
document.writeln("            </p>");
document.writeln("        </div>");
document.writeln("    </div>");
document.writeln("</div>");
document.writeln("<div class=\'bottomIn-bar\'>");
document.writeln("    <div class=\'bottomIn\'>");
document.writeln("        <div class=\'bottomIn-itemBar\'>");
document.writeln("");
document.writeln("            <div class=\'bottomIn-item\'>");
document.writeln("                <h2>About Us</h2>");
document.writeln("                <ul class=\'bottomIn-Con\'>");
document.writeln("                    <li>");
document.writeln("                        <a href=\'javascript:void(0)\'>Press Site</a>");
document.writeln("                    </li>");
document.writeln("                    <li>");
document.writeln("                        <a href=\'join.html\' target=\'_blank\'>Join Us</a>");
document.writeln("                    </li>");
document.writeln("                    <li>");
document.writeln("                        <a href=\'javascript:void(0)\'>Friend Links</a>");
document.writeln("                    </li>");
document.writeln("                </ul>");
document.writeln("            </div>");
document.writeln("");
document.writeln("");
document.writeln("            <div class=\'bottomIn-item\'>");
document.writeln("                <h2>Developer Service</h2>");
document.writeln("                <ul class=\'bottomIn-Con\'>");
document.writeln("                    <li>");
document.writeln("                        <a href=\'https://dev.mguwp.net/main/index\' target=\'_blank\'>Registration</a>");
document.writeln("                    </li>");
document.writeln("                    <li>");
document.writeln("                        <a href=\'https://doc.mguwp.net/\' target=\'_blank\'>Documents</a>");
document.writeln("                    </li>");
document.writeln("                    <li>");
document.writeln("                        <a href=\'javascript:void(0)\'>Tech Forum</a>");
document.writeln("                    </li>");
document.writeln("                </ul>");
document.writeln("            </div>");
document.writeln("");
document.writeln("            <div class=\'bottomIn-weChat\'>");
document.writeln("                <img src=\'images/weChat.jpg\'>");
document.writeln("                <p>MIRACLE GAMES</p>");
document.writeln("                <P>WeChat Site</P>");
document.writeln("            </div>");
document.writeln("        </div>");
document.writeln("        <div class=\'bottomIn-mid\'>");
document.writeln("            <div class=\'bottomIn-mid1\'></div>");
document.writeln("            <div class=\'bottomIn-mid2\'></div>");
document.writeln("        </div>");
document.writeln("        <div class=\'bottomIn-copy\'>");
document.writeln("            <p>COPYRIGHT© 2016 MIRACLE GAMES LIMITED. ALL RIGHTS RESERVED. </p>");
document.writeln("            <p>Beijing ICP 16022485-2 | Article [2017]1979-172</p>");
document.writeln("        </div>");
document.writeln("    </div>");
document.writeln("</div>");
document.writeln("");